# Deploys Faucet on Azure for Dev Testnet
# Builds the Faucet network image, pushes the image to dockerhub and starts the Faucet on azure
#
# Faucet is a docker container.
# It exposes the following ports:
# HTTP:       80,
#
# Exposes the following addresses: (only accessible internally)
#  dev-testnet-faucet.uksouth.azurecontainer.io

name: '[M] Deploy Faucet Dev Testnet'

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: obscuronet/dev_faucet_testnet:latest
          file: ./Dockerfile

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: dev-testnet-faucet
          image: obscuronet/dev_faucet_testnet:latest
          name: dev-testnet-faucet
          location: 'uksouth'
          restart-policy: 'Never'
          environment-variables: PORT=80
          command-line: cmd/faucet --nodeHost dev-testnet.obscu.ro --pk ${{ secrets.FAUCET_PK }} --jwtSecret ${{ secrets.FAUCET_JWT_SECRET }}
          ports: '80'
          cpu: 2
          memory: 2

